version: '2'
services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    expose:
      - "3306"
#    ports:
#      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sharepoint
      MYSQL_DATABASE: dcim_portal_development
#      MYSQL_USER: root
#      MYSQL_PASSWORD: sharepoint
  redis:
    image: redis:latest
    expose:
      - "6379"
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile-sidekiq
      args:
        - http_proxy
        - https_proxy
    command: bundle exec sidekiq
    volumes:
      - .:/Rails_DCIM_Portal
    depends_on:
      - db
      - redis
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${http_proxy}
      DCIM_PORTAL_DATABASE_HOST: db
      DCIM_PORTAL_REDIS_HOST: redis
      FOREMAN_URL: "https://foreman/"
      FOREMAN_USERNAME: "admin"
      FOREMAN_PASSWORD: "sharepoint"
  web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    command: /Rails_DCIM_Portal/init.sh
    volumes:
      - .:/Rails_DCIM_Portal
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${http_proxy}
      DCIM_PORTAL_DATABASE_HOST: db
      DCIM_PORTAL_REDIS_HOST: redis
      FOREMAN_URL: "https://foreman/"
      FOREMAN_USERNAME: "admin"
      FOREMAN_PASSWORD: "sharepoint"
volumes:
    db_data:
