development:
  adapter: redis
  url: redis://<%= ENV['DCIM_PORTAL_REDIS_HOST'] || "localhost" %>:<%= ENV['DCIM_PORTAL_REDIS_PORT'] || '6379' %>/<%= ENV['DCIM_PORTAL_REDIS_DB_FOR_CABLE'] || '2' %>

test:
  adapter: async

production:
  adapter: redis
  url: redis://<%= ENV['DCIM_PORTAL_REDIS_HOST'] || "localhost" %>:<%= ENV['DCIM_PORTAL_REDIS_PORT'] || '6379' %>/<%= ENV['DCIM_PORTAL_REDIS_DB_FOR_CABLE'] || '2' %>
