development:
  adapter: redis
  url: redis://<%= ENV['DCIM_PORTAL_REDIS_HOST'] || "localhost" %>:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://<%= ENV['DCIM_PORTAL_REDIS_HOST'] || "localhost" %>:6379/1
