development:
  adapter: redis
  url: redis://<%=ENV['DCIM_PORTAL_CABLE_REDIS_HOST'] || "localhost" %>:<%= ENV['DCIM_PORTAL_CABLE_REDIS_PORT'] || '6379' %>/<%= ENV['DCIM_PORTAL_CABLE_REDIS_DB'] || '1' %>

test:
  adapter: test

production:
  adapter: redis
  url: redis://<%=ENV['DCIM_PORTAL_CABLE_REDIS_HOST'] || "localhost" %>:<%= ENV['DCIM_PORTAL_CABLE_REDIS_PORT'] || '6379' %>/<%= ENV['DCIM_PORTAL_CABLE_REDIS_DB'] || '1' %>
