default: &default
  url: <%= ENV['FOREMAN_URL'] %>
  password: <%= ENV['FOREMAN_PASSWORD'] %>
  username: <%= ENV['FOREMAN_USERNAME'] || 'admin' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

